[book]
title = "Keramics data format specifications"
authors = ["Joachim Metz"]
language = "en"
multilingual = false
src = "src"

[output.html]
additional-css = ["custom.css"]

[preprocessor.tables]
command = "cargo run --manifest-path=mdbook-tables/Cargo.toml --locked"
