[package]
authors.workspace = true
description = "Keramics decoding methods"
edition.workspace = true
license.workspace = true
name = "encoding"
publish = false
version.workspace = true

[lib]
name = "encoding"
path = "src/lib.rs"
