# Build from source.
name: build
on:
  pull_request:
  push:
permissions: read-all
env:
  CARGO_TERM_COLOR: always
jobs:
  cargo_build:
    strategy:
      matrix:
        include:
        - os: macos-latest
          build-args: "--features fuzzing"
        - os: ubuntu-latest
          build-args: "--features fuzzing"
        - os: ubuntu-latest
          build-args: "--features zlib"
        - os: windows-latest
          build-args: ""
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v6
    - name: Build
      run: cargo build --verbose ${{ matrix.build-args }}
    - name: Run tests
      env:
        RUST_BACKTRACE: 1
      run: cargo test --verbose
