# Check source.
name: lint
on: [push, pull_request]
permissions: read-all
env:
  CARGO_TERM_COLOR: always
jobs:
  black:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Check format of Python code
      uses: psf/black@stable
      with:
        options: "--check"
        src: "keramics-python"
  cargo_fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Check format of Rust code
      run: cargo fmt --check
  rumdl:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Install rumdl
      run: cargo install rumdl
    - name: Check format of Markdown documents
      run: rumdl check
