# Check source.
name: lint
on: [push, pull_request]
permissions: read-all
env:
  CARGO_TERM_COLOR: always
jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        components: rustfmt
    - name: Format check
      run: cargo fmt --check
