# Build Python module from source using tox.
name: python
on: [push, pull_request]
permissions: read-all
env:
  CARGO_TERM_COLOR: always
jobs:
  tox:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - python-version: '3.9'
          toxenv: 'py39'
        - python-version: '3.10'
          toxenv: 'py310'
        - python-version: '3.11'
          toxenv: 'py311'
        - python-version: '3.12'
          toxenv: 'py312'
        - python-version: '3.13'
          toxenv: 'py313'
        - python-version: '3.14'
          toxenv: 'py314'
    steps:
    - uses: actions/checkout@v4
    - name: Install build dependencies
      run: |
        sudo add-apt-repository universe &&
        sudo add-apt-repository -y ppa:deadsnakes/ppa &&
        sudo apt-get update &&
        sudo apt-get install -y python${{ matrix.python-version }} python${{ matrix.python-version }}-dev python${{ matrix.python-version }}-venv python3-pip python3-setuptools python3-setuptools-rust
    - name: Install tox
      run: |
        python3 -m pip install tox
    - name: Build Python module
      run: |
        cd keramics-python && tox -e${{ matrix.toxenv }}
